config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :novels
  end
  resources :reviews
  devise_for :users
  root "novels#index"
  resources :novels do
    collection do
  match 'search' => 'novels#search', via: [:get, :post], as: :search
end
  end
  resources :tags, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/novel.rb
class Novel < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  acts_as_taggable_on :tags
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :novels
         has_many :reviews, dependent: :destroy
         
 def admin?
   is_admin
 end

 def super_admin?
   is_super_admin
 end
end

app/controllers/admin/novels_controller.rb
class Admin::NovelsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy]
before_action :require_is_admin
layout "admin"
  def show
    @novel = Novel.find(params[:id])
  end

  def index
    @novels = Novel.all
  end

  def new
    @novel = Novel.new
  end

  def create
    @novel = Novel.new(novel_params)
    @novel.user = current_user
    if @novel.save
      redirect_to admin_novels_path
    else
      render :new
    end
  end

  def edit
    @novel = Novel.find(params[:id])
  end

  def update
    @novel = Novel.find(params[:id])
    if @novel.update(novel_params)
      redirect_to admin_novels_path
    else
      render :edit
    end
  end

  def destroy
    @novel = Novel.find(params[:id])

    @novel.destroy

    redirect_to admin_novels_path
  end
  


  private

  def novel_params
    params.require(:novel).permit(:title, :description, :author, :lead, :comment, :tag_list)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  before_filter :set_search
  
  def set_search
    @q = Novel.search(params[:q])
  end
  
  def require_is_admin
    if !current_user.admin?
      flash[:alert] = 'You are not admin'
      redirect_to root_path
    end
  end
  
  
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController
  before_action :find_novel, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, only: [:new, :edit, :destroy, :create]
  
  
def index
    @q = Novel.search(params[:q])
  @novels = @q.result
end

 def search
  index
  render :index
 end

  
  def new
    @novel = Novel.new
  end
  
  def create
    @novel = Novel.new(novel_params)
    @novel.user = current_user
    if @novel.save
      redirect_to @novel, notice: "Successfully Saved"
    else
      render 'new', notice: "Oh no,"
    end
  end
  
  def edit
  end
  
  def update
    if @novel.update(novel_params)
      redirect_to @novel, notice: "Successfully saved"
    
    else
      render 'edit'
    end
  end
  
  def show
  end
  
  def destroy
    @novel.destroy
    flash[:alert] = "Novel deleted"
    redirect_to novels_path
  end
  
  private
  
  def find_novel
    @novel = Novel.find(params[:id])
    if current_user != @novel.user
      redirect_to root_path, alert: "You have no permission"
    end
  end
  
  def novel_params
    params.require(:novel).permit(:title, :description, :author, :lead, :comment, :tag_list)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = ActsAsTaggableOn::Tag.all
  end

  def show
    @tag =  ActsAsTaggableOn::Tag.find(params[:id])
    @novels = Novel.tagged_with(@tag.name)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/admin/novels_helper.rb
module Admin::NovelsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/novels_helper.rb
module NovelsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/acts_as_taggable_on/tags/_tag.html.erb
<%= link_to tag.name, tag_path(tag) %>

app/views/admin/novels/_form.html.erb
<%= simple_form_for [:admin, @novel] do |f| %>
  <div class="form-group">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :tag_list, value: f.object.tag_list.to_s %>
    <%= f.input :author %>
    <%= f.input :lead %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/admin/novels/_novel.html.erb
<h2><%= link_to novel.title, novel_path(novel) %></h2>

app/views/admin/novels/edit.html.erb
<h2>Edit Novel</h2>
<%= render "form" %>

app/views/admin/novels/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New Novel", new_admin_novel_path, class:"btn btn-outline-primary float-right") %>
  </div>
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">author</th>
      <th scope="col">Tags</th>
      <th scope="col">Creator</th>
    </tr>
  </thead>
  <tbody>
    <% @novels.each do |novel| %>
    <tr>
      <td>#</td>
      <td><%= link_to(novel.title, admin_novel_path(novel), class: "text-dark", style: "text-decoration: none;") %></td>
      <td><%= novel.author %></td>
      <td><%= render novel.tags %></td>
      <td><%= novel.user.email %></td>
      <td>
        <% if current_user && current_user == novel.user %>
        <%= link_to("Edit", edit_admin_novel_path(novel), class: "btn btn-outline-info") %>
        <%= link_to("Delete", admin_novel_path(novel), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?"}) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
  
</div>

app/views/admin/novels/new.html.erb
<h2>New Novel</h2>
<%= render "form" %>

app/views/admin/novels/show.html.erb
<div class="group">
  <% if current_user && current_user == @novel.user %>
  <%= link_to("Edit", edit_novel_path(@novel), class: "btn btn-outline-primary float-right") %>
  <% end %>
</div>
<h2><%= @novel.title %></h2>
<p> 作者：<%= @novel.author %></p>
<div><%= render @novel.tags %></div>
<p>简介：
   <br>
  <%= @novel.description %></p>
<p>
  主角：<%= @novel.lead %></p>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2017 Novel101
        <br>Design by
        <a href="#" target=_new>luonayin</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="/">Novel101</a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">最热门 <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">最多收藏</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">最新发布</a>
      </li>
    </ul>
    <form class="form-inline" >
      <div class="form-group">
              <%= search_form_for @q, url: search_novels_path, html: {method: :post, class: "navbar-form"} do |f| %>
      </div>

    <p class="form-group mx-sm-3">
      <%= f.text_field :title_cont, class: "form-control" %>
      <%= f.submit "Search", class: "btn btn-outline-success mx-2" %>
    </p>
  <% end %>
    </form>
      
    <% if !current_user %>
      <li><%= link_to("注册", new_user_registration_path) %> </li>
      <li><%= link_to("登录", new_user_session_path) %></li>
    <% else %>
      <li class="dropdown">
       <a href="#" class="dropdown-toggle btn btn-success" data-toggle="dropdown">
            Hi!, <%= current_user.email %>
        <b class="caret"></b>
        </a>
       <ul class="dropdown-menu">
         <% if current_user.admin? %>
         <li class="dropdonw-item"><%= link_to("Admin Panel", admin_novels_path) %> </li>
         <% end %>
        <li class="dropdown-item"> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
       </ul>
      </li>
    <% end %>

</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title> Novel Listing </title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>

        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg navbar-light fixed-top" style="background-color: #e3f2fd;">
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
              <a class="navbar-brand" href="/">Novel101</a>
              <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                  <a class="nav-link" href="#">我所发表的文章 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">我的收藏</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">正在追踪的小说</a>
                </li>
              </ul>
              
                

                 <ul class="dropdown-menu">
                   <% if current_user.admin? %>
                   <li class="dropdonw-item"><%= link_to("Admin Panel", admin_novels_path) %> </li>
                   <% end %>
                  <li class="dropdown-item"> <%= link_to("退出", destroy_user_session_path, method: :delete) %> </li>
                 </ul>
                

          </nav>
          <br>
          <br>
          <br>
          <br>
            <div class="row">
              <div class="col-md-2">
                <ul class="nav flex-column nav-pills" >
   <li class="active nav-link text-light bg-dark"><%= link_to("Novels", admin_novels_path ) %> </li>

</ul>
              </div>

              <div class="col-md-10">
                <%= yield %>
              </div>
           </div>
        </div>

        <%= render "common/footer" %>

    </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Novels101</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= render "common/navbar" %>
      <br>
      <br>
      <br>
      <div class="container">
        <%= yield %>
      </div>
      
    </div>
  <%= render "common/footer" %>
  </body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>

app/views/novels/_form.html.erb
<%= simple_form_for @novel do |f| %>
  <div class="form-group">
    <%= f.input :title %>
    <%= f.input :description %>
    
    <%= f.input :author %>
    <%= f.input :lead %>
    
  </div>
  <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submiting..." } %>
<% end %>

app/views/novels/_novel.html.erb
<h2><%= link_to novel.title, novel_path(novel) %></h2>

app/views/novels/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New Novel", new_novel_path, class:"btn btn-outline-primary float-right") %>
  </div>
  <table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Tags</th>
      <th scope="col">author</th>
      <th scope="col">Creator</th>
    </tr>
  </thead>
  <tbody>
    <% @novels.each do |novel| %>
    <tr>
      <td>#</td>
      <td><%= link_to(novel.title, novel_path(novel), class: "text-dark", style: "text-decoration: none;") %></td>
      <td><%= render novel.tags %></td>
      <td><%= novel.author %></td>
      <td><%= novel.user.email %></td>
      <td>
        <% if current_user && current_user == novel.user %>
        <%= link_to("Edit", edit_novel_path(novel), class: "btn btn-outline-info") %>
        <%= link_to("Delete", novel_path(novel), class: "btn btn-outline-danger", method: :delete, data: { confirm: "Are you sure?"}) %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
  
</div>

app/views/novels/show.html.erb
<div class="group">
  <% if current_user && current_user == @novel.user %>
  <%= link_to("Edit", edit_novel_path(@novel), class: "btn btn-outline-primary float-right") %>
  <% end %>
</div>
<h2><%= @novel.title %></h2>
<div><%= render @novel.tags %></div>
<p> 作者：<%= @novel.author %></p>
<p>简介：
   <br>
  <%= @novel.description %></p>
<p>
  主角：<%= @novel.lead %></p>

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :rating %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Rating</th>
      <th scope="col">Comment</th>
      <th scope="col">User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.user.email %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user.email %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/tags/index.html.erb
<h1>Tags</h1>
<%= render @tags %>

app/views/tags/show.html.erb
<h1><%= @tag.name %></h1>
<div><%= render @novels %></div>

app/views/welcome/index.html.erb
<div class="alert alert-success" role="alert">
  This is a primary alert—check it out!
</div>

<h1>Hello World</h1>